# Source: kuberhealthy/templates/khcheck-deployment.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
    kuberhealthy-run-id: '124800ae-15ff-4cd4-9ebe-560d605a38a5'
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - name: deployment
        image: kuberhealthy/deployment-check:v1.9.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_DEPLOYMENT_REPLICAS
            value: "4"
          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
            value: "true"
          - name: CHECK_SERVICE_ACCOUNT
            value: "default"
          - name: KH_RUN_UUID
            value: "124800ae-15ff-4cd4-9ebe-560d605a38a5"
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 40m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        restartPolicy: Never
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
