filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/jxquickstart
  version: 0.0.1
  name: jxquickstart
  values:
  - jx-values.yaml
- chart: dev/jxquickstart2
  version: 0.0.1
  name: jxquickstart2
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
